name: Cabot Scheduler Cron

on:
  schedule:
    - cron: '*/5 * * * *'   # Cada 5 minutos
  workflow_dispatch:       # Permite ejecutarlo manualmente

jobs:
  send-scheduled-email:
    runs-on: ubuntu-latest

    steps:
      - name: Llamar endpoint cron del backend
        run: |
          curl -X POST https://cabot-scheduler-laboratory.onrender.com/cron/check-and-send
